version: '3.7'
services:
  db:
    container_name: db
    networks:
      - my-network-name
    image: mysql
    volumes:
      - ./db-init/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 3307:3306
  web:
    networks:
      - my-network-name
    build: .
    image: springbootdemo_web
    ports:
      - 3333:8080
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    depends_on:
      - db
      
networks:
  my-network-name:
   name: my-global-net
volumes:
  mySqlData: